version: '3.1'

services:

  postgress11:
    image: postgres:11
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./dbinit://docker-entrypoint-initdb.d:ro
    environment:
      POSTGRES_PASSWORD: example

